services:
  verifier-backend:
    container_name: verifier-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/data
    networks:
      - my_shared_network
    restart: unless-stopped

  verifier-frontend:
    container_name: verifier-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5176:80"
    depends_on:
      - verifier-backend
    networks:
      - my_shared_network
    restart: unless-stopped

networks:
  my_shared_network:
    external: true